# Header
rss: /atom.xml
twitter: https://twitter.com/@KellenPiffner
google_plus: https://plus.google.com/109745187704465695599/about
github: https://github.com/decoy
linked_in: http://www.linkedin.com/in/kellenpiffner


# Content
excerpt_link: Read More

# Miscellaneous
google_analytics: UA-47279370-1
google_analytics_site: piffner.com

favicon: /favicon.ico
